# Generated by Django 2.0.5 on 2018-06-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DouBanBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pub', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('star', models.FloatField()),
                ('category', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='doubanbook',
            index=models.Index(fields=['name'], name='app_doubanb_name_aa10d9_idx'),
        ),
    ]
